/* Generated by the Admin panel. Do not edit manually. */
window.PUBLISHED_CONTENT = {
  version: 1,
  publishedAt: null,
  profile: null,
  skills: null,
  learning: null,
  education: null,
  certifications: null,
  experience: null,
  projects: []
};